import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Status Education Centre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`${nunitoSans.variable} font-[family-name:var(--font-nunito-sans)] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
